{% set name = "eradicate" %}
{% set version = "2.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eradicate-{{ version }}.tar.gz
  sha256: 06df115be3b87d0fc1c483db22a2ebb12bcf40585722810d809cc770f5031c37

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - eradicate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/myint/eradicate
  summary: Removes commented-out code.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
