{% set name = "eradicate" %}
{% set version = "2.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eradicate-{{ version }}.tar.gz
  sha256: c329a05def6a4b558dab58bb1b694f5209706b7c99ba174d226dfdb69a5ba0da

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - eradicate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/myint/eradicate
  summary: Removes commented-out code.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
