{% set name = "eradicate" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/eradicate-{{ version }}.tar.gz
  sha256: aac7384ab25b1bf21c4c012de9b4bf8398945a14c98c911545b2ea50ab558014

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - eradicate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/myint/eradicate
  summary: Removes commented-out code.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
