schema_version: 1

context:
  name: eradicate
  version: 3.0.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/eradicate-${{ version }}.tar.gz
  sha256: b237d9f2309b181035d2a87b24385b4f11ab7bb858b75bff496964b5f453aa77

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - eradicate
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Removes commented-out code.
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/myint/eradicate

extra:
  recipe-maintainers:
    - thewchan
